# Generated by Django 3.0.7 on 2020-07-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('nickname', models.CharField(max_length=20)),
                ('callname', models.CharField(max_length=100)),
                ('givenname', models.CharField(max_length=100)),
                ('suffix', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
