# Generated by Django 3.0.7 on 2020-07-04 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200704_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthdate',
            field=models.DateField(default=datetime.date(1960, 1, 1)),
        ),
        migrations.AddField(
            model_name='person',
            name='deathdate',
            field=models.DateField(default=datetime.date(1960, 1, 1)),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_filter/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1),
        ),
    ]
