# Generated by Django 3.0.7 on 2020-07-04 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200704_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='children',
            field=models.ManyToManyField(related_name='_person_children_+', to='app.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='father',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Father', to='app.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Mother', to='app.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='spouse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Spouse', to='app.Person'),
        ),
    ]
