# Generated by Django 3.0.7 on 2020-07-04 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200704_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='father',
            field=models.ForeignKey(default=None, limit_choices_to={'gender': 'M'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Father', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(default=None, limit_choices_to={'gender': 'F'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mother', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='spouse',
            field=models.ForeignKey(default=None, limit_choices_to={'gender': ''}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Spouse', to='app.Person'),
        ),
    ]
