# Generated by Django 3.0.7 on 2020-07-04 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200704_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='callname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='_person_children_+', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='father',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'gender': 'M'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Father', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'gender': 'F'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mother', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='origin',
            field=models.CharField(blank=True, choices=[('P', 'Patrilineal'), ('I', 'Inherited'), ('M', 'Matrilineal'), ('T', 'Taken')], max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='social',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='spouse',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'gender': ''}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Spouse', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
