# Generated by Django 3.0.7 on 2020-07-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200704_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
