# Generated by Django 3.0.7 on 2020-07-05 01:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200705_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='U', max_length=10),
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(blank=True, max_length=10)),
                ('marriagedate', models.DateField(default=datetime.date(1960, 1, 1))),
                ('children', models.ManyToManyField(blank=True, related_name='_family_children_+', to='app.Family')),
                ('husband', models.ForeignKey(blank=True, default=None, limit_choices_to={'gender': 'M'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Husband', to='app.Person')),
                ('wife', models.ForeignKey(blank=True, default=None, limit_choices_to={'gender': 'F'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Wife', to='app.Family')),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
    ]
