# Generated by Django 3.0.7 on 2020-07-05 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200705_0118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Family',
        ),
    ]
