# Generated by Django 3.0.7 on 2020-07-05 01:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(blank=True, max_length=10)),
                ('marriagedate', models.DateField(default=datetime.date(1960, 1, 1))),
                ('children', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Children', to='app.Person')),
                ('husband', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Husband', to='app.Person')),
                ('wife', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Wife', to='app.Person')),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
    ]
