# Generated by Django 3.0.7 on 2020-07-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='children',
        ),
        migrations.AddField(
            model_name='family',
            name='children',
            field=models.ManyToManyField(default=None, null=True, to='app.Person'),
        ),
    ]
