# Generated by Django 3.0.7 on 2020-07-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200705_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='children',
            field=models.ManyToManyField(default=None, to='app.Person'),
        ),
    ]
