# Generated by Django 3.0.7 on 2020-07-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200705_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='given',
            new_name='givenname',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='sibling',
        ),
        migrations.AlterField(
            model_name='family',
            name='children',
            field=models.ManyToManyField(default=None, null=True, to='app.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='_person_children_+', to='app.Person'),
        ),
    ]
