# Generated by Django 3.0.7 on 2020-07-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200705_0418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='person',
            new_name='person_id',
        ),
        migrations.AlterField(
            model_name='person',
            name='children',
            field=models.ManyToManyField(blank=True, to='app.Person'),
        ),
    ]
