# Generated by Django 3.0.7 on 2020-07-19 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200705_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='personid',
            new_name='person_id',
        ),
    ]
